-- /home/aibot/code/toolkit/database/migrations/000002_add_analytics_last_fetched_at_to_synack_targets.down.sql
-- SQLite does not support simple DROP COLUMN.
-- To reverse this, you would need to:
-- 1. PRAGMA foreign_keys=off;
-- 2. CREATE TABLE synack_targets_new AS SELECT id, synack_target_id_str, ... (all columns EXCEPT analytics_last_fetched_at) FROM synack_targets;
-- 3. DROP TABLE synack_targets;
-- 4. ALTER TABLE synack_targets_new RENAME TO synack_targets;
-- 5. PRAGMA foreign_keys=on;
-- This is complex and data-loss prone if not done carefully.
-- For this example, we'll acknowledge the column would remain if rolling back.
SELECT 'SQLite does not easily support DROP COLUMN. Column analytics_last_fetched_at would remain if this down migration is run.';
