CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    color TEXT, -- Optional color for the tag (e.g., hex code like #FF0000)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS tags_updated_at
AFTER UPDATE ON tags FOR EACH ROW
BEGIN UPDATE tags SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id; END;